
version: '3.8'

services:

  server:
    build:
      context: .
      target: final

    ports:
      - 8080:8080

    env_file:
      - .env.test

    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3